services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://milenarosa:random@db:5432/webhook-server
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=milenarosa
      - POSTGRES_PASSWORD=random
      - POSTGRES_DB=webhook-server
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: